version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:EyxIBgpwhuonZjFtZQMSrEDmlmOBIkOL@junction.proxy.rlwy.net:35120/railway
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./uploads:/usr/src/app/uploads
