version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./uploads:/usr/src/app/uploads
    command: [ "sh", "-c", "npx prisma migrate deploy && npm run start:prod" ]
